name: Github Actions
run-name: ${{ github.actor }} is quicksort
on: [push]
jobs:
  ErgonomicWorks:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."


  GithubActions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."




  Shift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Run Integrations
        run: cargo test
      
      - name: Build project
        run: cargo build
      
      - name: Run project
        run: cargo run
        
      
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      



  Latest-Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Run Integrations
        run: cargo test
      
      - name: Build project
        run: cargo build
      
      - name: Run project
        run: cargo run
        
      
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      



