name: Github Actions
run-name: ${{ github.actor }} is quicksorting
on: [push]
jobs:
  Ergonomic-Works:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."


  Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."




  Shift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Run Integrations
        run: cargo test
      
      - name: Build project
        run: cargo build
      
      - name: Run project
        run: cargo run
        
      
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      



  Latest-Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}
      APP_VERSION: 1.0.1
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        
      - name: Install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-pc-windows-msvc
        
      - name: Build
        #run: echo "token"
        env:
          APP_VERSION: ${{env.APP_VERSION}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          command: build
          #args: --no-default-features --features cli
          args: --no-default-features --release --target x86_64-pc-windows-msvc
        
      
      - name: Run Integrations
        run: cargo test
      
      - name: Build project
        run: cargo build
      
      - name: Run project
        run: cargo run
        
      
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      



